export const en = {
  WEEKDAYS_ABBR: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  WEEKDAYS: [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ],
  MONTHS_ABBR: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  MONTHS: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  timeAgo: {
    justNow: "Just now",
    minute: (min: number) => `${min} minute${min > 1 ? "s" : ""} ago`,
    hour: (hours: number) => `${hours} hour${hours > 1 ? "s" : ""} ago`,
    day: (days: number) => `${days} day${days > 1 ? "s" : ""} ago`,
  },
};

export const th = {
  WEEKDAYS_ABBR: ["อา", "จ", "อ", "พ", "พฤ", "ศ", "ส"],
  WEEKDAYS: [
    "อาทิตย์",
    "จันทร์",
    "อังคาร",
    "พุธ",
    "พฤหัสบดี",
    "ศุกร์",
    "เสาร์",
  ],
  MONTHS_ABBR: [
    "ม.ค.",
    "ก.พ.",
    "มี.ค.",
    "เม.ย.",
    "พ.ค.",
    "มิ.ย.",
    "ก.ค.",
    "ส.ค.",
    "ก.ย.",
    "ต.ค.",
    "พ.ย.",
    "ธ.ค.",
  ],
  MONTHS: [
    "มกราคม",
    "กุมภาพันธ์",
    "มีนาคม",
    "เมษายน",
    "พฤษภาคม",
    "มิถุนายน",
    "กรกฎาคม",
    "สิงหาคม",
    "กันยายน",
    "ตุลาคม",
    "พฤศจิกายน",
    "ธันวาคม",
  ],
  timeAgo: {
    justNow: "เมื่อสักครู่",
    minute: (min: number) => `${min} นาทีที่แล้ว`,
    hour: (hours: number) => `${hours} ชั่วโมงที่แล้ว`,
    day: (days: number) => `${days} วันที่ผ่านมา`,
  },
};

export const ONE_DAY_IN_MILLISECONDS = 8.64e7;
